import Head from "next/head";
import NavBar from "../components/common/navagation/NavBar";
import Footer from "../components/common/navagation/Footer";
import Header from "../components/page-sections/home-page/Header";
import Courses from "../components/page-sections/home-page/Courses";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Header />
      <Courses />
      <Footer />
    </div>
  );
}
